import { useMemo } from 'react';
import { ArrowDownToLine } from 'lucide-react';
import rawDrafts from '@/data/interview-staging/medicine-expansion.json';
import { assembleCircuit, CIRCUIT_PROFILES } from '@/interview/medicine-content/expansion/circuit';
import research from '@/interview/medicine-content/expansion/research.json';
import type { MedicineDraft } from './ExpansionLab';

const drafts=rawDrafts as MedicineDraft[];
type Notes=Record<string,{note:string;decision:string;updatedAt:string}>;
function download(name:string,body:string,type:string){const url=URL.createObjectURL(new Blob([body],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ContentCoverage({notes}:{notes:Notes}){
  const topics=useMemo(()=>[...new Set(drafts.map(q=>q.topic))].sort().map(topic=>({topic,rows:drafts.filter(q=>q.topic===topic)})),[]);
  const capacity=useMemo(()=>CIRCUIT_PROFILES.map(profile=>{const seen:string[]=[];let count=0;for(let i=0;i<100;i++){const result=assembleCircuit(drafts,profile,{seed:400+i,seenIds:seen});if(result.ok===false)break;count++;seen.push(...result.plan.stations.map(s=>s.stationId));}return {name:profile.name,count,used:seen.length};}),[]);
  const ready=drafts.filter(q=>notes[q.id]?.decision==='ready-for-review').length;
  const revision=drafts.filter(q=>notes[q.id]?.decision==='needs-revision').length;
  function exportPack(){download('medicine-editorial-review-pack.json',JSON.stringify({exportedAt:new Date().toISOString(),purpose:'Editorial review only; not a runtime import or publication manifest',researchEdition:research.edition,questions:drafts.map(q=>({...q,localReviewerNote:notes[q.id]??null})),sources:research.sources},null,2),'application/json');}
  function exportReadable(){const body=['# Medicine editorial review pack','',`Exported ${new Date().toISOString()}. ${drafts.length} original drafts. Human review required before publication.`,...drafts.flatMap(q=>['',`## ${q.title}`,`ID: ${q.id} | ${q.topic} | ${q.tracks.join(' / ')} | difficulty ${q.difficulty}`,'','### Candidate prompt',q.question,'','### Reasoning guide',q.answer,'','### Follow-up ladder',...q.liveProbes.flatMap((p,i)=>[`${i+1}. ${p.probe}`,`   Guidance: ${p.goodResponse}`]),'','### Assessment bands',...Object.entries(q.rubric).map(([band,text])=>`- ${band}: ${text}`),'',`Review owners: ${q.reviewRequired.join(', ')}.`,`Local decision: ${notes[q.id]?.decision??'unreviewed'}`,`Reviewer note: ${notes[q.id]?.note??'None'}`])].join('\n');download('medicine-editorial-review-pack.md',body,'text/markdown');}
  return <section className="lab-section lab-coverage" id="content-coverage"><div className="lab-section-title"><div><h2>Content coverage & review</h2><p>See where the bank has depth, what needs review and how many distinct complete circuits a rehearsal simulation can assemble.</p></div><span>{drafts.length} STAGED · 0 PUBLISHED FROM THIS BATCH</span></div><div className="lab-coverage-summary"><div><strong>{ready}</strong><span>Ready for editorial review</span></div><div><strong>{revision}</strong><span>Revisions requested</span></div><div><strong>{drafts.length-ready-revision}</strong><span>Awaiting a decision here</span></div><div><strong>{drafts.filter(q=>q.tracks.length>1).length}</strong><span>Shared across both tracks</span></div></div><div className="lab-coverage-grid"><div className="lab-coverage-table"><table><thead><tr><th>CONTENT AREA</th><th>ACADEMIC</th><th>MMI</th><th>REVIEW READY</th></tr></thead><tbody>{topics.map(({topic,rows})=><tr key={topic}><td>{topic.replace(/-/g,' ')}</td><td>{rows.filter(q=>q.tracks.includes('academic')).length}</td><td>{rows.filter(q=>q.tracks.includes('mmi')).length}</td><td>{rows.filter(q=>notes[q.id]?.decision==='ready-for-review').length} / {rows.length}</td></tr>)}</tbody></table><p>Shared drafts appear in both track columns. “Review ready” is your browser’s editorial handoff decision, not publication approval.</p></div><div className="lab-capacity"><h3>Practice without repeats</h3>{capacity.map(row=><div key={row.name}><span>{row.name}</span><b>{row.count} circuits</b><small>{row.used} distinct drafts used</small></div>)}<p>A reproducible simulation with standard and stretch drafts. This shows achievable sequences, not every possible combination. History is separate for each simulation.</p></div></div><div className="lab-evidence-warning"><b>Release work still open:</b> science/admissions review and a deployed live-model/avatar acceptance run. The three admin pilots now have planned circuits, distinct guidance and feedback rubrics. Application session budgets cover the full practice plan; the avatar account must support those durations. Backend migration and deployment are required for the new server controls.</div><div className="lab-pack-actions"><button className="lab-primary" onClick={exportPack}><ArrowDownToLine size={16}/>Export full review pack</button><button onClick={exportReadable}><ArrowDownToLine size={16}/>Export readable version</button><span>Includes original prompts, follow-ups, rubrics and your local notes.</span></div></section>;
}
