import { useMemo, useState } from 'react';
import { ArrowUpRight, Search } from 'lucide-react';
import map from '@/interview/medicine-content/data/uk-medical-school-interview-map.json';
import evidence from '@/interview/medicine-content/expansion/evidence.json';
import research from '@/interview/medicine-content/expansion/research.json';

const refreshed = new Map(evidence.formats.map((row) => [row.id,row]));
const sources = new Map(research.sources.map((row) => [row.id,row]));
export default function SchoolEvidenceExplorer() {
  const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [route,setRoute]=useState('all');const [limit,setLimit]=useState(9);
  const filtered=useMemo(()=>map.schools.filter((s)=>(`${s.university} ${s.course} ${s.code} ${s.interview_type}`.toLowerCase().includes(query.toLowerCase()))&&(status==='all'||(status==='refreshed'?refreshed.has(s.id):!refreshed.has(s.id)))&&(route==='all'||(route==='graduate'?s.route.toLowerCase().includes('graduate')&&!s.route.toLowerCase().includes('undergraduate'):s.route.toLowerCase().includes('undergraduate')))).sort((a,b)=>Number(refreshed.has(b.id))-Number(refreshed.has(a.id))),[query,status,route]);
  return <section className="lab-section lab-evidence" id="school-evidence"><div className="lab-section-title"><div><h2>The school evidence register</h2><p>{map.schools.length} course routes in the existing map. {evidence.formats.length} refreshed format records, with source access and remaining questions visible.</p></div><span>{filtered.length} MATCHING ROUTES</span></div>
    <div className="lab-evidence-controls"><label className="lab-search"><Search size={16}/><input aria-label="Search school evidence" placeholder="Search university, course or format…" value={query} onChange={(e)=>{setQuery(e.target.value);setLimit(9);}}/></label><select aria-label="Evidence freshness" value={status} onChange={(e)=>{setStatus(e.target.value);setLimit(9);}}><option value="all">All evidence</option><option value="refreshed">Refreshed this edition</option><option value="inherited">Awaiting refresh</option></select><select aria-label="Course route" value={route} onChange={(e)=>{setRoute(e.target.value);setLimit(9);}}><option value="all">All course routes</option><option value="undergraduate">Undergraduate</option><option value="graduate">Graduate entry</option></select></div>
    <div className="lab-evidence-grid">{filtered.slice(0,limit).map((s)=>{const fresh=refreshed.get(s.id);const source=fresh?sources.get(fresh.sourceId):undefined;return <article className="lab-evidence-card" key={s.id}><span className={`lab-evidence-label ${fresh?'':'lab-evidence-inherited'}`}>{fresh?fresh.access==='full'?'OFFICIAL PAGE RETRIEVED':'OFFICIAL INDEXED EVIDENCE':'INHERITED · AWAITING REFRESH'}</span><h3>{s.university}</h3><p>{s.code} · {s.course}</p><dl><div><dt>Format</dt><dd>{fresh?.type??s.interview_type}</dd></div><div><dt>Cycle in evidence</dt><dd>{fresh?.cycle??s.cycle_published}</dd></div><div><dt>Structure</dt><dd>{fresh?.structure??'See inherited notes'}</dd></div><div><dt>Timing</dt><dd>{fresh?.timing??'Not refreshed'}</dd></div></dl><p>{fresh?.summary??'This route is searchable from the existing research map. Its details have not been revalidated in this edition.'}</p><details><summary>Limitations & source details</summary><p>{fresh?.unknowns??s.structure}</p><p>{fresh?source?.access:s.confidence} · {fresh?.checked??s.date_checked}</p>{fresh&&<p>Delivery: {fresh.delivery}.</p>}<a href={source?.url??s.source_url} target="_blank" rel="noreferrer">Official reference <ArrowUpRight size={14}/></a></details></article>;})}</div>
    {!filtered.length&&<div className="lab-empty">No routes match these filters.</div>}{filtered.length>limit&&<button className="lab-primary lab-evidence-more" onClick={()=>setLimit(limit+12)}>Show 12 more routes</button>}
    <div className="lab-selectivity"><h3>How competitive are they?</h3><p>Start with Oxford, Cambridge and Imperial as requested. For the next wave, UCL, King’s, Edinburgh and St Andrews have useful published evidence. These figures describe different cycles and populations; they do not establish a UK-wide “hardest to enter” ranking or an individual applicant’s chance.</p><div className="lab-selectivity-scroll" role="region" aria-label="Admissions evidence comparison" tabIndex={0}><table><thead><tr><th>SCHOOL / COURSE</th><th>CYCLE / POPULATION</th><th>APPLICATIONS</th><th>OFFERS</th><th>DERIVED OFFER FRACTION</th></tr></thead><tbody>{evidence.metrics.map((row,i)=><tr key={`${row.school}-${i}`}><td><a href={sources.get(row.sourceId)?.url} target="_blank" rel="noreferrer">{row.school} ↗</a><small>{row.course}</small></td><td>{row.cycle}<small>{row.population}</small></td><td>{row.applications?.toLocaleString('en-GB')??'Not supplied'}</td><td>{row.offers?.toLocaleString('en-GB')??'Not comparable'}</td><td>{row.offers!==null&&row.applications!==null?`${(100*row.offers/row.applications).toFixed(1)}%`:('ratio' in row&&row.ratio?`${row.ratio} applications / place`:'Withheld')}<small>{row.note}</small></td></tr>)}</tbody></table></div><div className="lab-evidence-warning"><b>Unresolved source discrepancy:</b> Edinburgh’s 2025 overall row lists 585 offers, while its Scottish, rest-of-UK and international rows sum to 661. The application-count footnote also differs from the headline. An overall offer percentage is deliberately withheld pending clarification.</div></div>
  </section>;
}
