import { ArrowRight, AudioLines, Check, Clock3, MessageSquare, Mic, Stethoscope } from 'lucide-react';
import { INTERVIEW_TYPES } from '@/config/interviewTypes';
import './medicine-landing-clinical.css';

const modes = [INTERVIEW_TYPES['medicine-mmi'], INTERVIEW_TYPES['medicine-mmi-manchester']];
export function MedicineLandingClinical() {
  return <div className="med-landing">
    <header className="med-landing-nav"><a className="med-wordmark" href="/"><span className="med-logo-mark"><Stethoscope size={19}/></span>intrvue<span>.</span>ai</a><nav aria-label="Medicine landing"><a href="#how-it-works">How it works</a><a href="#formats">Practice formats</a><a href="#feedback">Feedback</a></nav><div><a href="/auth?mode=medicine">Log in</a><a className="med-landing-primary" href="/auth?mode=medicine">Start practising <ArrowRight size={15}/></a></div></header>
    <main>
      <section className="med-landing-hero"><div><span className="med-landing-eyebrow">MEDICINE INTERVIEW PRACTICE</span><h1>Say it out loud<br/>before it counts.</h1><p>Think on your feet. Find the words. Practise a spoken medicine interview with Clara, then get feedback you can put to work.</p><div className="med-landing-actions"><a className="med-landing-primary" href="/auth?mode=medicine">Start practising <ArrowRight size={17}/></a><a className="med-landing-secondary" href="#how-it-works">See how it works</a></div><div className="med-landing-proof"><div><strong>2</strong><span>timed school modes</span></div><div><strong>8</strong><span>practice strands</span></div><div><strong>Your voice</strong><span>your reasoning, out loud</span></div></div></div><div className="med-landing-avatar"><div className="med-avatar-caption"><span/> Clara · your practice interviewer</div>{/* TODO: approved 1040×960 Clara still, dark clinical backdrop, eye-level framing. */}<div className="med-avatar-placeholder"><div><AudioLines size={48}/></div><span>YOUR NEXT CONVERSATION STARTS HERE</span><small>Clara image placeholder · 1040 × 960</small></div><div className="med-landing-report"><div><MessageSquare size={19}/><span>Feedback that moves you forward</span></div><p>What worked. What needs attention.<br/>A clear next step for your practice.</p></div></div></section>
      <section className="med-landing-section" id="how-it-works"><span className="med-landing-eyebrow">A SIMPLE PRACTICE ROUTINE</span><h2>Prepare by doing.</h2><div className="med-landing-three">{[{n:'01',title:'Choose your focus',text:'Run a timed Leeds-style or Manchester-style circuit, or focus on a station type.'},{n:'02',title:'Have the conversation',text:'Explain your thinking aloud. Respond to follow-ups. Practise adapting when the question changes.'},{n:'03',title:'Know what to work on',text:'Read your written feedback, reflect on the reasoning and return with a specific practice goal.'}].map((s)=><article key={s.n}><b>{s.n}</b><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
      <section className="med-landing-section med-landing-formats" id="formats"><div><span className="med-landing-eyebrow">STRUCTURE YOU CAN PRACTISE</span><h2>Different formats.<br/>One shared question bank.</h2><p>Published timing guides the two current modes. Original practice questions build transferable skills; they are not a reproduction of real admissions questions.</p></div><div>{modes.map((m)=><article key={m.id}><div><span className="med-landing-eyebrow">TIMED CIRCUIT</span><h3>{m.name.replace('Medicine MMI — ','')}</h3></div><p><Clock3 size={16}/>{m.timingSeconds!.response/60} min per station · {m.timingSeconds!.prep ? `${m.timingSeconds!.prep/60} min reading` : 'no reading time'}</p><a href={m.verifiedAgainst!.sourceUrl} target="_blank" rel="noreferrer">Published university format ↗</a></article>)}</div></section>
      <section className="med-landing-section med-landing-feedback" id="feedback"><div><span className="med-landing-eyebrow">TURN REFLECTION INTO PROGRESS</span><h2>More than a score.<br/>Something to use.</h2><p>Feedback considers your reasoning, communication, professional judgement and reflection. See what came through clearly and where your next answer could go further.</p><ul>{['Ground your answer in a specific example.','Explain the trade-off, then justify your position.','Show how new information changes your thinking.'].map((t)=><li key={t}><Check size={17}/>{t}</li>)}</ul></div><article className="med-example-feedback"><span className="med-landing-eyebrow">ILLUSTRATIVE FEEDBACK · NOT A STUDENT RESULT</span><h3>A clearer next attempt.</h3><div><span>WHAT WORKED</span><p>You considered more than one perspective and explained the reason for your choice.</p></div><div><span>TRY NEXT TIME</span><p>Make the example more specific. Say what information would make you change your decision.</p></div><p className="med-example-note">Practice feedback supports reflection. Admissions decisions and scoring remain with each university.</p></article></section>
      <section className="med-landing-closing"><div><span className="med-landing-eyebrow">A LITTLE MORE READY</span><h2>Your next interview<br/>starts with a conversation.</h2></div><a href="/auth?mode=medicine"><Mic size={19}/>Start practising<ArrowRight size={17}/></a></section>
    </main><footer className="med-landing-footer"><span>intrvue.ai · Medicine</span><span>Independent practice. Not affiliated with or endorsed by the named universities.</span></footer>
  </div>;
}
