-- Seed the "Chat with Clara" question bank into the DB-backed questions table, so it's editable
-- from Admin -> Questions without a code deploy (interview-brain prefers the DB over the bundled
-- JSON bank when rows exist for a subject — see supabase/functions/interview-brain/index.ts loadBank).
-- Mirrors src/interview/bank/questions/chat/**/*.json; ON CONFLICT makes this safe to re-run.
insert into public.questions (id, subject, topic, question_type, difficulty, title, question, answer, model_reasoning_path, tags)
values
  ('CHAT-A1', 'chat', 'about-you', 'About You', 2, 'Tell Me About Yourself',
   'So, tell me a little bit about yourself — your family, where you live, whatever feels natural to share.',
   'Discussion question — there is no single correct answer. Assess warmth, openness and specific detail, not content.',
   'What to listen for: specific, concrete detail (names, places, particular family members or routines) versus a generic one-line answer. Note anything specific enough to come back to later — a sibling''s name, a pet, a place they live, a hobby they mention in passing.',
   '{}'),
  ('CHAT-A2', 'chat', 'about-you', 'About You', 2, 'A Typical Day',
   'What does a normal day look like for you, from when you wake up to when you go to bed?',
   'Discussion question — there is no single correct answer. Assess specific, genuine detail versus a vague generic routine.',
   'What to listen for: do they mention anything specific and personal (a particular after-school activity, a routine with a family member, something they look forward to) worth remembering and possibly returning to later.',
   '{}'),
  ('CHAT-A3', 'chat', 'about-you', 'About You', 2, 'Who You Spend Time With',
   'Who do you spend most of your time with, and what do you usually get up to together?',
   'Discussion question — there is no single correct answer. Assess warmth and specific detail about relationships.',
   'What to listen for: a named person (friend, sibling, grandparent) and a specific shared activity — this is excellent callback material later in the chat.',
   '{}'),
  ('CHAT-A4', 'chat', 'about-you', 'About You', 2, 'Somewhere You Love',
   'Is there somewhere — a place, a room, a spot outside — that feels really special to you? What makes it special?',
   'Discussion question — there is no single correct answer. Assess genuine reflection versus a surface-level answer.',
   'What to listen for: a real, specific reason the place matters (not just ''it''s nice'') — genuine reflection is the strong signal here.',
   '{}'),
  ('CHAT-I1', 'chat', 'interests-hobbies', 'Interests & Hobbies', 2, 'What You Love Doing',
   'What''s something you absolutely love doing — the thing that if you had a completely free afternoon, you''d choose to do?',
   'Discussion question — there is no single correct answer. Assess genuine enthusiasm and specific detail.',
   'What to listen for: a SPECIFIC named interest (a sport, an instrument, a subject, a game, drawing, reading a particular series) rather than something vague. This is the single best moment in the whole chat to flag for a possible later bonus callback question — if they name something like maths, chess, football, an instrument, remember it clearly.',
   '{}'),
  ('CHAT-I2', 'chat', 'interests-hobbies', 'Interests & Hobbies', 2, 'Getting Good At Something',
   'Is there something you''ve worked hard at and gotten better at over time? Tell me about it.',
   'Discussion question — there is no single correct answer. Assess specific detail and genuine reflection on effort/progress.',
   'What to listen for: a real example of practice and improvement, not just a claimed skill — asking ''how long have you been doing that?'' as a natural, genuine follow-up works well here.',
   '{}'),
  ('CHAT-I3', 'chat', 'interests-hobbies', 'Interests & Hobbies', 2, 'How You Got Into It',
   'How did you first get into the thing you''re most into right now? What got you hooked?',
   'Discussion question — there is no single correct answer. Assess a specific origin story versus a vague non-answer.',
   'What to listen for: a real, specific memory or moment (someone who introduced them to it, a first time trying it) — genuine stories here are exactly the kind of detail worth a warm callback later.',
   '{}'),
  ('CHAT-I4', 'chat', 'interests-hobbies', 'Interests & Hobbies', 2, 'Something New',
   'If you could instantly become brilliant at one new thing you''ve never tried, what would you pick?',
   'Discussion question — there is no single correct answer. Assess genuine, specific curiosity versus a generic answer.',
   'What to listen for: whether they give a specific choice with a real reason, versus ''I don''t know'' — a gentle, warm nudge to say more is appropriate if the first answer is very short.',
   '{}'),
  ('CHAT-F1', 'chat', 'favourites-and-fun', 'Favourites & Fun', 2, 'Favourite Subject',
   'What''s your favourite subject at school at the moment, and what do you like about it?',
   'Discussion question — there is no single correct answer. Assess specific reasoning versus a bare one-word answer.',
   'What to listen for: a real reason, not just the subject name. If they name maths, science, or a subject with a clear ''quick fun question'' angle, this is a strong candidate for the one light bonus callback question later — remember it clearly.',
   '{}'),
  ('CHAT-F2', 'chat', 'favourites-and-fun', 'Favourites & Fun', 2, 'A Book or Story You Loved',
   'Tell me about a book, story or film that you really loved — what was it about it that stuck with you?',
   'Discussion question — there is no single correct answer. Assess specific detail versus a generic title-only answer.',
   'What to listen for: can they say something specific about WHY it stuck with them, not just name it. A genuine, enthusiastic answer here is a strong signal, and a great thing to reference later.',
   '{}'),
  ('CHAT-F3', 'chat', 'favourites-and-fun', 'Favourites & Fun', 2, 'What Makes You Laugh',
   'What''s something that always makes you laugh, no matter what?',
   'Discussion question — there is no single correct answer. Assess genuine, specific personality versus a vague answer.',
   'What to listen for: this question exists to let real personality come through — a specific, genuine answer (an in-joke, a person, a type of humour) is a strong signal of warmth and openness.',
   '{}'),
  ('CHAT-F4', 'chat', 'favourites-and-fun', 'Favourites & Fun', 2, 'Proud Moment',
   'What''s something you''re genuinely proud of — big or small?',
   'Discussion question — there is no single correct answer. Assess genuine reflection versus a rehearsed or generic answer.',
   'What to listen for: specificity and genuine feeling, not a polished ''achievement list'' answer — a small, honest moment they''re proud of is just as strong a signal as a big one.',
   '{}')
on conflict (id) do update set
  subject = excluded.subject,
  topic = excluded.topic,
  question_type = excluded.question_type,
  difficulty = excluded.difficulty,
  title = excluded.title,
  question = excluded.question,
  answer = excluded.answer,
  model_reasoning_path = excluded.model_reasoning_path,
  tags = excluded.tags,
  updated_at = now();
